In [24]:
import pandas as pd

# Carregando o dataset
df = pd.read_csv("heart_disease_dataset.csv")

display(df.head())
print(df.info())

# essa aqui tem valores faltando, estou normalizando
df['Alcohol Intake'] = df['Alcohol Intake'].fillna("None")

# transformei dados que são strings, em true ou false
df_transformado = pd.get_dummies(df, drop_first=True)

display(df_transformado.head())

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB
None

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Heart Disease,Gender_Male,Smoking_Former,Smoking_Never,Alcohol Intake_Moderate,Alcohol Intake_None,Family History_Yes,Diabetes_Yes,Obesity_Yes,Exercise Induced Angina_Yes,Chest Pain Type_Atypical Angina,Chest Pain Type_Non-anginal Pain,Chest Pain Type_Typical Angina
0,75,228,119,66,1,8,119,1,False,False,False,False,False,False,False,True,True,True,False,False
1,48,204,165,62,5,9,70,0,True,False,False,False,True,False,False,False,True,False,False,True
2,53,234,91,67,3,5,196,1,True,False,True,False,False,True,False,True,True,True,False,False
3,69,192,90,72,4,7,107,0,False,False,False,False,True,False,True,False,True,False,True,False
4,62,172,163,93,6,2,183,0,False,False,True,False,True,False,True,False,True,False,False,False

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df_transformado.drop('Heart Disease', axis=1)
y = df_transformado['Heart Disease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_padronizado = scaler.fit_transform(X_train)
X_test_padronizado = scaler.transform(X_test)

print("Tamanho do X_train:", X_train_padronizado.shape)
print("Tamanho do X_test:", X_test_padronizado.shape)

Tamanho do X_train: (800, 19)
Tamanho do X_test: (200, 19)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

modelo_lr = LogisticRegression()
modelo_lr.fit(X_train_padronizado, y_train)

modelo_knn = KNeighborsClassifier(n_neighbors=5)
modelo_knn.fit(X_train_padronizado, y_train)

print("Modelos treinados com sucesso!")

Modelos treinados com sucesso!

In [30]:
from sklearn.metrics import accuracy_score, classification_report

preditos_lr = modelo_lr.predict(X_test_padronizado)
preditos_knn = modelo_knn.predict(X_test_padronizado)

acc_lr = accuracy_score(y_test, preditos_lr)
acc_knn = accuracy_score(y_test, preditos_knn)

print(f"Acurácia Regressão Logística: {acc_lr * 100:.2f}%")
print(f"Acurácia KNN: {acc_knn * 100:.2f}%\n")

print("--- Relatório da Regressão Logística ---")
print(classification_report(y_test, preditos_lr))

print("--- Relatório do KNN ---")
print(classification_report(y_test, preditos_knn))

Acurácia Regressão Logística: 87.00%
Acurácia KNN: 77.50%

--- Relatório da Regressão Logística ---
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       118
           1       0.85      0.83      0.84        82

    accuracy                           0.87       200
   macro avg       0.87      0.86      0.87       200
weighted avg       0.87      0.87      0.87       200

--- Relatório do KNN ---
              precision    recall  f1-score   support

           0       0.79      0.85      0.82       118
           1       0.75      0.67      0.71        82

    accuracy                           0.78       200
   macro avg       0.77      0.76      0.76       200
weighted avg       0.77      0.78      0.77       200

In [31]:
import numpy as np
import matplotlib.pyplot as plt

pesos = np.abs(modelo_lr.coef_[0])

importancia = pd.DataFrame({
    'Característica': X.columns,
    'Peso': pesos
}).sort_values(by='Peso')

print("mais difíceis de aprender")
display(importancia.head())

mais difíceis de aprender

             Característica      Peso
10  Alcohol Intake_Moderate  0.015625
13             Diabetes_Yes  0.025841
9             Smoking_Never  0.029337
14              Obesity_Yes  0.035835
11      Alcohol Intake_None  0.041711